# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='detalle',
        ),
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.ManyToManyField(to='facturacion.Producto'),
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
    ]
