# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20170719_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='rtn',
            new_name='rtnProveedor',
        ),
    ]
