# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20170720_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='correoContacto',
            new_name='emailContacto',
        ),
    ]
